### PR TITLE
hLXaDTmX-Logout a user  

### PR DESCRIPTION
**Pull request by GuevaraMarius**
#### What does this PR do?
  - Logout to Phantom
#### Description of Task to be completed?
 - Authenticated users are able to logout.
 - Appropriate error messages are displayed on unsuccessful attempts
- Skeleton UIs/screen are/is shown when the page loads/is loading.
- The app layouts are displayed
- The page is responsive.
#### How should this be manually tested?
- checkout this branch
- run npm install
- sign in a user
- click logout
#### What are the relevant trello id?
hLXaDTmX

### CODE REVIEW

**Review by samuel776 — COMMENTED** [review]
congrats to this work, can you work on the deployment please

**Review by mansurissa — DISMISSED** [review]
LGTM

**Review by Egide138 — DISMISSED** [review]

**Review by 41hulk — APPROVED** [review]
LGTM

**Review by mansurissa — APPROVED** [review]
Good Job

**Review by SIBONIYO — APPROVED** [review]

**Review by raymond42 — APPROVED** [review]

**Pull request merged**
