### PR TITLE
BjQmh9rH set up continuous integration and heroku deployment 

### PR DESCRIPTION
**Pull request by samuel776**
#### What does this PR do?
   - Setup Continuous Integration & Quality Assurance pipeline
#### Description of Task to be completed?
 - configure testing environment with jest and enzyme
 - configure github actions for continuous
- configure heroku pipeline on heroku
- configure codeclimate
- coveralls for pr checking
#### How should this be manually tested?
- clone it to the local repo
- run npm install
- test the home page by running npm test
#### What are the relevant trello id?
[BjQmh9rH](https://trello.com/c/BjQmh9rH/27-setup-continuous-integration-quality-assurance-pipeline)

### CODE REVIEW

**Review by mansurissa — DISMISSED** [review]
LGTM

**Comment by raymond42** [comment]
@samuel776 can you check the test coverage badge? it's not displaying the coverage

**Review by KundwaBruno — DISMISSED** [review]

**Review by mansurissa — DISMISSED** [review]
Good job

**Review by SIBONIYO — DISMISSED** [review]
good work man

**Review by GuevaraMarius — APPROVED** [review]

**Review by mansurissa — APPROVED** [review]

**Review by KundwaBruno — APPROVED** [review]

**Review by raymond42 — APPROVED** [review]
LGTM

**Pull request merged**
