### PR TITLE
Oi7E45Vb Landing Page

### PR DESCRIPTION
**Pull request by KundwaBruno**
### What does this PR do?
This PR adds a landing Page which will act as a reference to a theme for the application
### Tasks to be completed
The Landing Page is implemented.
The Landing Page is responsive.
### How should this be manually tested?
Clone this branch and run` npm install` to install all dependecies.
Then start your application with `npm run dev`
### Relevant Trello Story
ID: Oi7E45Vb

### CODE REVIEW

**Review by mansurissa — DISMISSED** [review]
Good Job man(you've been debuging alot :))

**Review by 41hulk — DISMISSED** [review]
Good Job Bruno(bugman🐞)

**Review by GuevaraMarius — DISMISSED** [review]

**Review by GuevaraMarius — DISMISSED** [review]

**Review by mansurissa — DISMISSED** [review]
Good job bug man

**Review by GuevaraMarius — APPROVED** [review]

**Review by GuevaraMarius — DISMISSED** [review]

**Review by Egide138 — DISMISSED** [review]

**Review by raymond42 — DISMISSED** [review]

**Review by samuel776 — DISMISSED** [review]

**Review by raymond42 — DISMISSED** [review]

**Review by GuevaraMarius — DISMISSED** [review]

**Review by raymond42 — APPROVED** [review]
LGTM. nice work @KundwaBruno

**Review by GuevaraMarius — APPROVED** [review]

**Review by samuel776 — APPROVED** [review]

**Pull request merged**
